app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/seerr/seerr
            tag: latest
          env:
            TZ: Europe/Amsterdam
  service:
    main:
      controller: main
      ports:
        http:
          port: 5055
  persistence:
    config:
      existingClaim: seerr-config
      globalMounts:
        - path: /app/config
