app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/flaresolverr/flaresolverr
            tag: latest
          env:
            TZ: Europe/Amsterdam
  service:
    main:
      controller: main
      ports:
        http:
          port: 8191
