app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/flaresolverr/flaresolverr
            tag: latest@sha256:c80ae007ce2ccdcd217a12426e4f039ef763ff90738c808d38810c3e59323767
          env:
            TZ: Europe/Amsterdam
  service:
    main:
      controller: main
      ports:
        http:
          port: 8191
