app-template:
  defaultPodOptions:
    securityContext:
      fsGroup: 1000
  controllers:
    main:
      containers:
        main:
          image:
            repository: seerr/seerr
            tag: latest@sha256:27602401178d54f1964442287b9f23f67a3fa2252645ee8065839ea1c3f69e45
          env:
            TZ: Europe/Amsterdam
  service:
    main:
      controller: main
      ports:
        http:
          port: 5055
  persistence:
    config:
      existingClaim: seerr-config
      globalMounts:
        - path: /app/config
