app-template:
  defaultPodOptions:
    securityContext:
      fsGroup: 1000
  controllers:
    main:
      containers:
        main:
          image:
            repository: seerr/seerr
            tag: latest
          env:
            TZ: Europe/Amsterdam
  service:
    main:
      controller: main
      ports:
        http:
          port: 5055
  persistence:
    config:
      existingClaim: seerr-config
      globalMounts:
        - path: /app/config
