app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/manimatter/decluttarr
            tag: latest
          env:
            TZ: Europe/Amsterdam
            RADARR_URL: http://radarr.media.svc.cluster.local:7878
            SONARR_URL: http://sonarr.media.svc.cluster.local:8989
            QBITTORRENT_URL: http://qbittorrent.media.svc.cluster.local:8080
          envFrom:
            - secretRef:
                name: decluttarr-credentials
  service:
    main:
      controller: main
      ports:
        http:
          port: 80
