app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: lscr.io/linuxserver/bazarr
            tag: latest@sha256:8b30e81c4aec2991f469e78fae8afaa89ecc9b21a80e3897f50427216b55470c
          env:
            TZ: Europe/Amsterdam
            PUID: "1000"
            PGID: "1000"
  service:
    main:
      controller: main
      ports:
        http:
          port: 6767
  persistence:
    config:
      existingClaim: bazarr-config
      globalMounts:
        - path: /config
    media:
      existingClaim: media-pvc
      globalMounts:
        - path: /media
