app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: lscr.io/linuxserver/bazarr
            tag: latest
          env:
            TZ: Europe/Amsterdam
            PUID: "1000"
            PGID: "1000"
  service:
    main:
      controller: main
      ports:
        http:
          port: 6767
  persistence:
    config:
      existingClaim: bazarr-config
      globalMounts:
        - path: /config
    media:
      existingClaim: media-pvc
      globalMounts:
        - path: /media
