apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: zitadel-db
  namespace: workout
spec:
  name: zitadel
  owner: zitadel
  cluster:
    name: workout-pg
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: forgejo-db
  namespace: workout
spec:
  name: forgejo
  owner: forgejo
  cluster:
    name: workout-pg
